force-app/main/default/objects/Asset/fields/CSS_properties__c.field-meta.xml
<CustomField>
    <fullName>CSS_properties__c</fullName>
    <label>CSS properties</label>
    <length>2500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Daily_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Daily_Mileage__c</fullName>
    <formula>IF ( TODAY() - InstallDate &gt; 0, Mileage__c /( TODAY() - InstallDate ), NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Daily Mileage</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Remaining_Life__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Life__c</fullName>
    <formula>IF (  Life_Expectancy__c &gt; 0,  1 - Mileage__c / Life_Expectancy__c , IF(Product2.Life_Expectancy__c &gt; 0, 1 - Mileage__c / Product2.Life_Expectancy__c , 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Life</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Replacement_Date__c.field-meta.xml
<CustomField>
    <fullName>Replacement_Date__c</fullName>
    <formula>IF( Daily_Mileage__c &gt; 0, TODAY() + (Life_Expectancy__c - Mileage__c) / Daily_Mileage__c, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Replacement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Walk_Around_Order__c.field-meta.xml
<CustomField>
    <fullName>Walk_Around_Order__c</fullName>
    <label>Walk Around Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset_Inspection__c/Asset_Inspection__c.object-meta.xml
<CustomObject>
    <label>Asset Inspection</label>
    <nameField>
        <displayFormat>AI-{000000}</displayFormat>
        <label>Asset Inspection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Inspections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Inspection__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Inspections</relationshipLabel>
    <relationshipName>Asset_Inspections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset_Telematic__c/Asset_Telematic__c.object-meta.xml
<CustomObject>
    <label>Asset Telematic</label>
    <nameField>
        <displayFormat>AT-{000000}</displayFormat>
        <label>Asset Telematic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Telematics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Telematic__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Telematics</relationshipLabel>
    <relationshipName>Asset_Telematics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset_Telematic__c/fields/Measure_Name__c.field-meta.xml
<CustomField>
    <fullName>Measure_Name__c</fullName>
    <label>Measure Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset_Telematic__c/fields/Measure_Time__c.field-meta.xml
<CustomField>
    <fullName>Measure_Time__c</fullName>
    <label>Measure Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset_Telematic__c/fields/Measure_Value__c.field-meta.xml
<CustomField>
    <fullName>Measure_Value__c</fullName>
    <label>Measure Value</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Life_Expectancy__c.field-meta.xml
<CustomField>
    <fullName>Life_Expectancy__c</fullName>
    <label>Life Expectancy</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_Image_URL__c</fullName>
    <description>Used by the Vehicle View LWC to display the Product image in the asset details panel when selecting an asset (a vehicle part).</description>
    <inlineHelpText>If image is an Asset File, use pattern such as: https://[your_domain].file.force.com/file-asset/[file_name]?oid=[your_org_id]</inlineHelpText>
    <label>Product Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Top_View_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Top_View_Image_URL__c</fullName>
    <label>Top View Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CANVehicleController.cls
public without sharing class CANVehicleController {
    
    @AuraEnabled(cacheable=true)
    public static Asset getVehicle(String assetId) {
        System.debug('getVehicle');
        return [SELECT Id, Name, AccountId, Product2.Top_View_Image_URL__c FROM Asset WHERE Id = :assetId];
    }

    @AuraEnabled(cacheable=true)
    public static List<sObject> getAssetIdByVehicleId(String vehicleId) {
        System.debug('getAssetIdByVehicleId');
        try {
            return Database.query('SELECT AssetId FROM Vehicle WHERE Id = :vehicleId');
        } catch(QueryException e) {
            // object or field does not exist
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static WorkOrder getAssetIdByWorkOrderId(String workOrderId) {
        System.debug('getAssetIdByWorkOrderId');
        return [SELECT AssetId FROM WorkOrder WHERE Id = :workOrderId];
    }

    @AuraEnabled(cacheable=true)
    public static Case getAssetIdByCaseId(String caseId) {
        System.debug('getAssetIdByCaseId');
        return [SELECT AssetId FROM Case WHERE Id = :caseId];
    }

    @AuraEnabled(cacheable=true)
    public static Asset getAsset(String assetId) {
        System.debug('getAsset');
        return [SELECT Id, Name, AccountId, Product2.Top_View_Image_URL__c FROM Asset WHERE Id = :assetId];
    }

    @AuraEnabled
    public static List<Asset> getVehiclePartsFromAsset(String assetId) {
        System.debug('get vehicle parts from asset id');
        return [SELECT Id, Name, CSS_properties__c, SerialNumber, ProductFamily, Product2.Product_Image_URL__c, Product2.Life_Expectancy__c, Life_Expectancy__c, Remaining_Life__c, InstallDate, Daily_Mileage__c, Replacement_Date__c, Walk_Around_Order__c FROM Asset WHERE ParentId = :assetId ORDER BY Walk_Around_Order__c];
    }

    @AuraEnabled
    public static Boolean updateAsset(Asset tireAsset) {
        try {
            update tireAsset;
            return true;
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            return false;
        }
        
    }

    @AuraEnabled
    public static String saveOpty(Opportunity opty, List<OpportunityLineItem> optyLineItemList){
        try {
            System.debug('insert opportunity');
            insert opty;
            for(OpportunityLineItem opli:optyLineItemList){
                opli.OpportunityId = opty.Id;
            }
            insert optyLineItemList;
            System.debug('inserted opportunity : ' + opty.Id);
            return opty.Id;
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            return '';
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Asset_Telematic__c> getTelematics(String assetId) {
        System.debug('get telematics');
        return [SELECT Id, Name, Asset__c, Measure_Name__c, Measure_Time__c, Measure_Value__c FROM Asset_Telematic__c WHERE Asset__c = :assetId ORDER BY Measure_Time__c];
    }

    @AuraEnabled
    public static string insertTelematics(Asset_Telematic__c assetTelematic){
        try {
            insert assetTelematic;
            return assetTelematic.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Pricebook2> getPriceBookList(){
        try {
            return [SELECT Id, Name FROM Pricebook2];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static PriceBookEntry getPriceBookEntry(String productId, String pricebookId){
        try {
            return [SELECT Id, UnitPrice FROM PriceBookEntry WHERE Product2Id = :productId AND Pricebook2Id = :pricebookId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static string insertAssetInspection(Asset_Inspection__c assetInspection){
        try {
            insert assetInspection;
            return assetInspection.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}